apiVersion: v1
kind: Service
metadata:
  name: keapser-service
spec:
  type: NodePort
    ports:
      - port: 9090
          - targetPort: 9090
            name: authentication-service-port
    selector:
      app: keapser-service



