language: java


jdk:
  - openjdk11
  - openjdk15

os: linux
dist: trusty

branches:
  only:
    - dev
    - /^us.*$/

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

before_script:
  - docker-compose up -d --build

script:
  - docker-compose run test

after_script:
  - docker-compose down

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_KEY
    app: keapser
    on:
      branch: master
      jdk: 11
  skip_cleanup: true

notifications:
  email:
    recipients:
      - keapser-chat@groups.outlook.com
    on_error: change
    on_success: always
