version: '3.3'

networks:
  keapsernet:
    driver: bridge
  backendnet:
    driver: bridge

volumes:
  keapser_service_db: { }

services:
    keapser-service-db:
      container_name: keapser_service_db
      image: postgres:11.5
      ports:
        - 2021:5432
      networks:
        - keapsernet

    keapser-service:
      container_name: keapser_service
      build: keapser-service
      env_file:
        - keapser-service/.env
      ports:
        - 80:8080
      links:
        - "keapser-service-db:keapser-db"
      networks:
        - keapsernet
        - backendnet
      depends_on:
        - keapser-service-db
