apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-service
      spec:
        containers:
          -name:
            image:
            ports:
              - containerPort: 9090
            env:
              - name: PORT
                  value: 9090
